# Dockerfile.backend
FROM python:3.9-slim

WORKDIR /app

# Copy necessary files
COPY requirements.txt .
COPY app.py .
COPY model_v1.pt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
