# Dockerfile.backend
FROM python:3.9-slim

WORKDIR /app

# Copy application files
COPY requirements.txt .
COPY app.py .
COPY model.py .
COPY model_latest.pt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "app.py"]
