name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      MODEL_FILE: "serialized_models/model_v1.pt" 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      MODEL_FILE: "serialized_models/model_v1.pt"  
      RAILWAY_DEPLOY_WEBHOOK: ${{ secrets.RAILWAY_DEPLOY_WEBHOOK }}  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Trigger Deployment on Railway
        run: |
          chmod +x deploy.sh
          ./deploy.sh
